version: "3.9"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: ./bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
      - postgres

  django:
    build: ./django_project
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"

volumes:
  redis:
  pgdata:
